services:
  server:
    build:
      context: .
    ports:
      - "80:80"
      - "443:443"
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./root/opt/echo/src:/opt/echo/src
      - ./root/var/www/example/:/var/www/example