ServerName localhost

<VirtualHost *:80>
    ServerName localhost
    DocumentRoot /var/www/example/public_html
    ErrorLog ${APACHE_LOG_DIR}/example_http_error.log
    CustomLog ${APACHE_LOG_DIR}/example_http_access.log combined
</VirtualHost>

<VirtualHost *:443>
    ServerName localhost
    DocumentRoot /var/www/example/public_html
    SSLEngine on
    SSLCertificateFile /etc/ssl/certs/example-public.pem
    SSLCertificateKeyFile /etc/ssl/private/example-private.pem
    ErrorLog ${APACHE_LOG_DIR}/example_https_error.log
    CustomLog ${APACHE_LOG_DIR}/example_https_access.log combined
</VirtualHost>